### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by bjaroszewska** [zajan/spring-blog#1]
I run the command:
 mvn spring-boot:run 

and I got the following error: 

<img width="1440" alt="Screenshot 2019-08-20 at 16 13 41" src="https://user-images.githubusercontent.com/9664535/63355032-cc682000-c365-11e9-9357-ca1758b99cd2.png">

" Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) on project spring-blog: An exception occurred while running. null: InvocationTargetException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution: Communications link failure
"

**Comment by zajan** [comment]
This issue occurs probably because your mysql db is not configured properly. I will change datasource to embedded one so it's easier for testing.

**Comment by zajan** [comment]
Datasource is changed to H2.
